---
title: "Relatório de Contas 2020"
author: "Vasco Pereira"
date: "`r Sys.Date()`"
#output: html_document
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

# Relatórios de Contas 

## Tratamento de dados do banco

```{r get and format data}
## Carregamento de bibliotecas
library(dplyr)
library(lubridate)
library(stringr)

## Extracção dos dados
dataFiles <- list.files("./2020/extratos", pattern = "csv$", full.names = TRUE)

contasDF <- tibble()

for (i in 1:length(dataFiles)){
        contasDF <- contasDF %>% bind_rows(read.delim(dataFiles[i], sep = ";"))
}

## Conversão para formato de data
tempDateMOV <- dmy(contasDF$DATA.MOV.[1:42])
tempDateVALOR <- dmy(contasDF$DATA.VALOR[1:42])

## Conversão para formato de data (alteração de outra formatação do banco)
tempDateMOV <- tempDateMOV %>% c(ymd(contasDF$DATA.MOV.[43:(length(contasDF$DATA.MOV.))]))
tempDateVALOR <- tempDateVALOR %>% c(ymd(contasDF$DATA.VALOR[43:(length(contasDF$DATA.VALOR))]))

## Correcção da coluna DATA.MOV. e DARA.VALOR
contasDF$DATA.MOV. <- tempDateMOV
contasDF$DATA.VALOR <- tempDateVALOR

## Correcção da formatação para valores numericos
contasDF$IMPORTÂNCIA <- contasDF$IMPORTÂNCIA %>% 
        str_replace_all("[.]", "") %>%
        str_replace_all("[,]", ".") %>%
        as.numeric()

## Correcção da formatação para valores numericos
contasDF$SALDO.CONTABILÍSTICO <- contasDF$SALDO.CONTABILÍSTICO %>% 
        str_replace_all("[.]", "") %>%
        str_replace_all("[,]", ".") %>%
        as.numeric()
```

# Automatização dos campos de Centro de Custo e Rúbricas   
## Centros de custo e rubricas existentes - GUIDELINES

```{r centros de custo e rubricas}
ccRubri <- read.delim("./2020/CentrosdeCusto.csv", sep = ";")
knitr::kable(ccRubri)
```


# Evolução do gasto/receita e Saldo

Gráfico da evolução do saldo(vermelho) e dos movimentos (azul), na conta da SUS.

```{r gasto e receita}
library(ggplot2)
ggplot(contasDF, aes(DATA.MOV., SALDO.CONTABILÍSTICO, IMPORTÂNCIA)) + 
        geom_line(aes(DATA.MOV., SALDO.CONTABILÍSTICO),color = "red") +
        geom_line(aes(DATA.MOV., IMPORTÂNCIA),color = "blue") +
        labs(x = "Data") + 
        labs(y = "Valor em Euros") + 
        labs(title = "Evolução Saldo e Movimentos") + 
        theme(plot.title = element_text(hjust = 0.5))
```


```{r adição de CC e Rubricas comuns}
## Securitas
if (sum(grepl("00026322892", contasDF$DESCRIÇÃO)) > 0) {
        contasDF <- mutate(contasDF, CENTRO.DE.CUSTO = ifelse(grepl("00026322892", DESCRIÇÃO), "ENCARGOS COM INSTALAÇÕES", "NA"))
        contasDF <- mutate(contasDF, RUBRICA = ifelse(grepl("00026322892", DESCRIÇÃO), "SECURITAS - ALARME", "NA"))
}

#SMAS
if (sum(grepl("96611566046", contasDF$DESCRIÇÃO)) > 0) {
        contasDF <- mutate(contasDF, CENTRO.DE.CUSTO = ifelse(grepl("96611566046", DESCRIÇÃO), "ENCARGOS COM INSTALAÇÕES", CENTRO.DE.CUSTO))
        contasDF <- mutate(contasDF, RUBRICA = ifelse(grepl("96611566046", DESCRIÇÃO), "CONSUMO ÁGUA (SMAS)", RUBRICA))
}

#Imposto de selo e despesas bancárias
if (sum(grepl("I.SELO|COMISSÃO MANUTENÇÃO", contasDF$DESCRIÇÃO)) > 0) {
        contasDF <- mutate(contasDF, CENTRO.DE.CUSTO = 
                                   ifelse(grepl("I.SELO|COMISSÃO MANUTENÇÃO", DESCRIÇÃO), 
                                          "ENCARGOS COM INSTALAÇÕES", CENTRO.DE.CUSTO))
        contasDF <- mutate(contasDF, RUBRICA = 
                                   ifelse(grepl("I.SELO|COMISSÃO MANUTENÇÃO", DESCRIÇÃO), "DESP. BANCÁRIAS", RUBRICA))
}

# VODAFONE
if (sum(grepl("00531446107", contasDF$DESCRIÇÃO)) > 0) {
        contasDF <- mutate(contasDF, CENTRO.DE.CUSTO = 
                                   ifelse(grepl("00531446107", DESCRIÇÃO), 
                                          "ENCARGOS COM INSTALAÇÕES", CENTRO.DE.CUSTO))
        contasDF <- mutate(contasDF, RUBRICA = 
                                   ifelse(grepl("00531446107", DESCRIÇÃO), "COMUNICAÇÕES", RUBRICA))
}

# MAFEP
if (sum(grepl("10367661", contasDF$DESCRIÇÃO)) > 0) {
        contasDF <- mutate(contasDF, CENTRO.DE.CUSTO = 
                                   ifelse(grepl("10367661", DESCRIÇÃO), 
                                          "ENCARGOS COM INSTALAÇÕES", CENTRO.DE.CUSTO))
        contasDF <- mutate(contasDF, RUBRICA = 
                                   ifelse(grepl("10367661", DESCRIÇÃO), "ALUGUER EXTINTORES", RUBRICA))
}


# EDP - CONSUMO ELECTRICIDADE Jesélia e SUS
if (sum(grepl("P05100001520", contasDF$DESCRIÇÃO)) > 0) {
        contasDF <- mutate(contasDF, CENTRO.DE.CUSTO = 
                                   ifelse(grepl("P05100001520", DESCRIÇÃO), 
                                          "ENCARGOS COM INSTALAÇÕES", CENTRO.DE.CUSTO))
        contasDF <- mutate(contasDF, RUBRICA = 
                                   ifelse(grepl("P05100001520", DESCRIÇÃO), "CONSUMO ELECTRICIDADE", RUBRICA))
}

# Seguros
if (sum(grepl("11034", contasDF$DESCRIÇÃO)) > 0) {
        contasDF <- mutate(contasDF, CENTRO.DE.CUSTO = 
                                   ifelse(grepl("11034", DESCRIÇÃO), 
                                          "ENCARGOS COM INSTALAÇÕES", CENTRO.DE.CUSTO))
        contasDF <- mutate(contasDF, RUBRICA = 
                                   ifelse(grepl("11034", DESCRIÇÃO), "SEGUROS", RUBRICA))
}

# Limpezas
if (sum(grepl("PT50000700000032524109823", contasDF$DESCRIÇÃO)) > 0) {
        contasDF <- mutate(contasDF, CENTRO.DE.CUSTO = 
                                   ifelse(grepl("PT50000700000032524109823", DESCRIÇÃO), 
                                          "ENCARGOS COM INSTALAÇÕES", CENTRO.DE.CUSTO))
        contasDF <- mutate(contasDF, RUBRICA = 
                                   ifelse(grepl("PT50000700000032524109823", DESCRIÇÃO), "SERVIÇO DE LIMPEZA", RUBRICA))
}

# Manutenção e Obras Gaspar Fontes
if (sum(grepl("PT50003501810000046033029", contasDF$DESCRIÇÃO)) > 0) {
        contasDF <- mutate(contasDF, CENTRO.DE.CUSTO = 
                                   ifelse(grepl("PT50003501810000046033029", DESCRIÇÃO), 
                                          "ENCARGOS COM INSTALAÇÕES", CENTRO.DE.CUSTO))
        contasDF <- mutate(contasDF, RUBRICA = 
                                   ifelse(grepl("PT50003501810000046033029", DESCRIÇÃO), "MANUTENÇÃO/OBRAS", RUBRICA))
}

# SPA
if (sum(grepl("PT50003300000000812850405", contasDF$DESCRIÇÃO)) > 0) {
        contasDF <- mutate(contasDF, CENTRO.DE.CUSTO = 
                                   ifelse(grepl("PT50003300000000812850405", DESCRIÇÃO), 
                                          "NOITE DAS CAMÉLIAS", CENTRO.DE.CUSTO))
        contasDF <- mutate(contasDF, RUBRICA = 
                                   ifelse(grepl("PT50003300000000812850405", DESCRIÇÃO), "IGAC / SPA", RUBRICA))
}

# Gás
if (sum(grepl("PT50003600509910031520496", contasDF$DESCRIÇÃO)) > 0) {
        contasDF <- mutate(contasDF, CENTRO.DE.CUSTO = 
                                   ifelse(grepl("PT50003600509910031520496", DESCRIÇÃO), 
                                          "ENCARGOS COM INSTALAÇÕES", CENTRO.DE.CUSTO))
        contasDF <- mutate(contasDF, RUBRICA = 
                                   ifelse(grepl("PT50003600509910031520496", DESCRIÇÃO), "GÁS", RUBRICA))
}

```


